require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# AactiveStorageのDBテーブル用に記述
MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/AbcSize:
  Max: 20

# app/model/microsoft.rb用に記述
Style/Lambda:
  EnforcedStyle: literal

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
  