<<<<<<< HEAD
# version: "3"
# services:
#   hello:
#     image: hello-world:latest
version: '3'
services:
  postgres:
    image: postgres:10-alpine
    # 任意のパスワード
    environment:
      POSTGRES_PASSWORD: password
    # ホスト側は任意のディレクトリ
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    # ホスト側は任意のポート
    ports:
      - 5432:5432
=======
version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: zsksample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
>>>>>>> c49f5849768201a53d7a93a3578c7bbc4cf96e27
