name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: polysoft/zsksample-rails-ci:latest

    steps:
      - uses: actions/checkout@v2
        with:
          # required to prevent shallow update errors on push
          fetch-depth: 0
      - name: Execute deploy
        shell: bash
        env:
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login ${HEROKU_LOGIN}
            password ${HEROKU_API_KEY}
          machine git.heroku.com
            login ${HEROKU_LOGIN}
            password ${HEROKU_API_KEY}
          EOF
          chmod 600 ~/.netrc
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
          heroku maintenance:on --app ${{ secrets.HEROKU_APP_NAME }}
          git push -f heroku master
          heroku run rake db:migrate --app ${{ secrets.HEROKU_APP_NAME }}
          heroku maintenance:off --app ${{ secrets.HEROKU_APP_NAME }}
